### ISSUE TITLE
Ability to set start time when adding a timer

### ISSUE THREAD

**Issue by chrisnharvey** [ben-styling/timekeys#4]
Like when editing a timer you can change the hours and minutes, it would be good if you could set these when adding a timer.

**Comment by ben-styling** [comment]
@chrisnharvey What use-cases would this cover?

**Comment by chrisnharvey** [comment]
When I forget to start a timer, I normally add one, and set it forward by 5-10 minutes.

**Comment by ben-styling** [comment]
That will be in the next release. Probably 11/11/19.

**Comment by ben-styling** [comment]
https://github.com/sibyl-systems/sibyl-timer/commit/68628583818cada12220c6bce3a5ccd184c17c43
